const money = value => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const productData = {
  1:['Perfume Diesel Only The Brave',25],2:['Trio Camisetas Surf',99.99],3:['Kit 3 Bermudas Quiksilver Azul',99.99],4:['Kit 3 Bermudas Surf Black',99.99],5:['Calça Jeans Destroyed Grafite',119.99],6:['Calça Jeans Jogador Sky',119.99],7:['Conjunto Mizuno Branco',89.99],8:['Bermuda Linho Areia',39.99],9:['Camisa Flamengo I',55],10:['Camisa Corinthians II',55],11:['Chinelo Slide Croco Preto',59.99],12:['Boné Mizuno Heritage',59.99],13:['Conjunto Street Grafite & Rosa',99.99],14:['Kit Gangster Navy',109.99],15:['Conjunto Street Black',99.99],16:['Camiseta Nike Minimal Black',69.99],17:['Kit Manchester City',99.99],18:['Kit Chelsea Away',99.99],19:['Camisa Cruzeiro Treino',69.99],20:['Look Essential Chumbo',149.99],21:['Chuteira Air Zoom Prata',249.99],22:['Chuteira Air Zoom Turquesa',249.99],25:['Kit Mizuno Cinza & Azul',149.99],26:['Kit Lacoste Branco & Verde',159.99],27:['Kit Lacoste Marinho',159.99]
};
let cart=JSON.parse(localStorage.getItem('compartilhe-cart')||'[]').filter(i=>productData[i.id]);
let deliveryType='pickup',shippingCost=0,shippingChoice=null,paymentMethod='pix',apiConfig={paymentsEnabled:false,shippingEnabled:false};
let paymentBrickController=null,paymentBrickAmount=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const subtotal=()=>cart.reduce((sum,item)=>sum+productData[item.id][1]*item.qty,0);
const total=()=>subtotal()+shippingCost;
const cleanDigits=value=>value.replace(/\D/g,'');

function renderSummary(){
  if(!cart.length){$('#summaryItems').innerHTML='<div class="summary-empty"><h3>Seu carrinho está vazio</h3><p>Adicione produtos antes de finalizar.</p><a class="btn btn--dark" href="catalogo.html">Ver catálogo</a></div>';$('#placeOrder').disabled=true}
  else $('#summaryItems').innerHTML=cart.map(item=>{const [name,price]=productData[item.id];return `<div class="summary-item"><img src="assets/products-clean/produto-${String(item.id).padStart(2,'0')}.webp" alt="${name}"><div><b>${name}</b><small>Tam. ${item.size} • Qtd. ${item.qty}</small></div><strong>${money(price*item.qty)}</strong></div>`}).join('');
  $('#summarySubtotal').textContent=money(subtotal());$('#summaryShipping').textContent=shippingCost?money(shippingCost):'Grátis';$('#summaryTotal').textContent=money(total());$('#placeOrderTotal').textContent=`${money(total())} →︎`;$('#installmentText').textContent=`ou 3x de ${money(total()/3)} sem juros`;
}

function setDelivery(type){deliveryType=type;$('#pickupPanel').hidden=type!=='pickup';$('#deliveryPanel').hidden=type!=='delivery';if(type==='pickup'){shippingCost=0;shippingChoice={name:'Retirada na loja',price:0,days:0};renderSummary();refreshPaymentBrick()}}
function setPayment(method){paymentMethod=method;$$('[data-payment]').forEach(b=>b.classList.toggle('active',b.dataset.payment===method));$$('[data-panel]').forEach(p=>{p.hidden=p.dataset.panel!==method;p.classList.toggle('active',p.dataset.panel===method)})}
function toast(text){$('#checkoutToast').textContent=text;$('#checkoutToast').classList.add('show');setTimeout(()=>$('#checkoutToast').classList.remove('show'),2600)}

async function lookupCep(){
  const cep=cleanDigits($('#postalCode').value);if(cep.length!==8){$('#postalCode').closest('.field').classList.add('invalid');return null}$('#postalCode').closest('.field').classList.remove('invalid');
  $('#shippingLoading').hidden=false;$('#shippingOptions').innerHTML='';
  try{const response=await fetch(`https://viacep.com.br/ws/${cep}/json/`);const address=await response.json();if(address.erro)throw new Error('CEP não encontrado');$('#street').value=address.logradouro||'';$('#neighborhood').value=address.bairro||'';$('#city').value=address.localidade||'';$('#stateUf').value=address.uf||'';$('#cepStatus').textContent=`${address.localidade}–${address.uf} • ${address.bairro||'Endereço localizado'}`;return address}catch(error){toast('Não foi possível localizar esse CEP.');return null}finally{$('#shippingLoading').hidden=true}
}

function fallbackOptions(address){const city=(address.localidade||'').toLowerCase();const uf=address.uf||'';if(city==='lavras')return[{id:'local',name:'Entrega local',price:8.9,days:'1–2 dias úteis'},{id:'local-express',name:'Entrega expressa Lavras',price:14.9,days:'Mesmo dia*'}];if(uf==='MG')return[{id:'economy',name:'Econômica',price:19.9,days:'3–6 dias úteis'},{id:'express',name:'Expressa',price:29.9,days:'1–3 dias úteis'}];if(['SP','RJ','ES'].includes(uf))return[{id:'economy',name:'Econômica',price:29.9,days:'5–9 dias úteis'},{id:'express',name:'Expressa',price:44.9,days:'2–5 dias úteis'}];return[{id:'economy',name:'Econômica',price:44.9,days:'7–14 dias úteis'},{id:'express',name:'Expressa',price:69.9,days:'4–8 dias úteis'}]}
async function calculateShipping(){
  const address=await lookupCep();if(!address)return;const cep=cleanDigits($('#postalCode').value);$('#shippingLoading').hidden=false;
  let options,source='estimate';try{const response=await fetch('/api/shipping-quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({destinationCep:cep,items:cart.map(i=>({id:i.id,quantity:i.qty,price:productData[i.id][1]}))})});if(response.ok){const data=await response.json();options=data.options;source=data.source||'api'}else throw new Error('API indisponível')}catch(error){options=fallbackOptions(address)}finally{$('#shippingLoading').hidden=true}
  $('#shippingOptions').innerHTML=options.map((o,index)=>`<label class="shipping-option"><input type="radio" name="shipping" value="${index}" ${index===0?'checked':''}><div><b>${o.name}</b><small>${o.company?o.company+' • ':''}${o.days}</small></div><strong>${money(Number(o.price))}</strong></label>`).join('')+`<div class="shipping-source">${source==='melhor-envio'?'Cotação em tempo real via Melhor Envio':'Estimativa automática • valor final depende da ativação da API'}</div>`;
  shippingChoice=options[0];shippingCost=Number(options[0].price);renderSummary();refreshPaymentBrick();$$('input[name=shipping]').forEach(input=>input.onchange=()=>{shippingChoice=options[Number(input.value)];shippingCost=Number(shippingChoice.price);renderSummary();refreshPaymentBrick()})
}

function validate(){let ok=true;[['#customerEmail',v=>/^\S+@\S+\.\S+$/.test(v)],['#customerName',v=>v.trim().split(/\s+/).length>1],['#customerCpf',v=>cleanDigits(v).length===11],['#customerPhone',v=>cleanDigits(v).length>=10]].forEach(([selector,test])=>{const input=$(selector);const valid=test(input.value);input.closest('.field').classList.toggle('invalid',!valid);if(!valid)ok=false});if(deliveryType==='delivery'){if(cleanDigits($('#postalCode').value).length!==8||!shippingChoice){toast('Calcule e escolha uma opção de entrega.');ok=false}if(!$('#addressNumber').value.trim()){toast('Informe o número do endereço.');ok=false}}if(!$('#termsCheck').checked){toast('Aceite os termos para continuar.');ok=false}return ok}

function loadMercadoPagoSdk(){return new Promise((resolve,reject)=>{if(window.MercadoPago)return resolve();const existing=document.querySelector('script[data-mercado-pago]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}const script=document.createElement('script');script.src='https://sdk.mercadopago.com/js/v2';script.dataset.mercadoPago='true';script.onload=resolve;script.onerror=()=>reject(new Error('Falha ao carregar o checkout seguro.'));document.head.appendChild(script)})}
async function processBrickPayment({formData}){
  if(!validate())throw new Error('Confira seus dados e aceite os termos.');
  const name=$('#customerName').value.trim().split(/\s+/);const payload={...formData,transaction_amount:Number(total().toFixed(2)),description:`Pedido Compartilhe Store (${cart.length} itens)`,payer:{...(formData.payer||{}),email:$('#customerEmail').value,first_name:name.shift()||'',last_name:name.join(' '),identification:{type:'CPF',number:cleanDigits($('#customerCpf').value)}},metadata:{deliveryType,shippingChoice,items:cart,phone:cleanDigits($('#customerPhone').value)}};
  const response=await fetch('/api/payment',{method:'POST',headers:{'Content-Type':'application/json','X-Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.message||'Pagamento não autorizado.');
  if(data.point_of_interaction?.transaction_data?.ticket_url){location.href=data.point_of_interaction.transaction_data.ticket_url;return}
  if(data.status==='approved'){localStorage.removeItem('compartilhe-cart');$('#checkoutModal h2').textContent='Pagamento aprovado.';$('#checkoutModal p').textContent='Seu pedido foi recebido e será preparado pela Compartilhe Store.';$('#checkoutModal').classList.add('open');$('#checkoutModal').setAttribute('aria-hidden','false');return}
  toast(`Pagamento ${data.status_detail||data.status||'em análise'}.`)
}
async function renderPaymentBrick(){
  if(!apiConfig.paymentsEnabled||!apiConfig.mercadoPagoPublicKey||!cart.length)return;
  try{await loadMercadoPagoSdk();if(paymentBrickController?.unmount)await paymentBrickController.unmount();$('#paymentBrickContainer').innerHTML='';$('#paymentManual').hidden=true;$('#paymentBrick').hidden=false;$('#placeOrder').hidden=true;paymentBrickAmount=Number(total().toFixed(2));const mp=new MercadoPago(apiConfig.mercadoPagoPublicKey,{locale:'pt-BR'});const builder=mp.bricks();paymentBrickController=await builder.create('payment','paymentBrickContainer',{initialization:{amount:paymentBrickAmount},customization:{paymentMethods:{creditCard:'all',debitCard:'all',bankTransfer:'all'}},callbacks:{onReady:()=>{$('#paymentMode').textContent='Mercado Pago ativo'},onSubmit:processBrickPayment,onError:error=>{console.error(error);toast('Não foi possível abrir o pagamento seguro.')}}})}catch(error){console.error(error);apiConfig.paymentsEnabled=false;$('#paymentMode').textContent='Integração indisponível';$('#paymentManual').hidden=false;$('#paymentBrick').hidden=true;$('#placeOrder').hidden=false}
}
function refreshPaymentBrick(){if(apiConfig.paymentsEnabled&&Math.abs(paymentBrickAmount-total())>.009)renderPaymentBrick()}
async function loadConfig(){try{const response=await fetch('/api/config');if(response.ok)apiConfig=await response.json()}catch{}if(apiConfig.paymentsEnabled){$('#paymentMode').textContent='Carregando Mercado Pago…';$('#paymentMode').classList.add('live');await renderPaymentBrick()}else{$('#paymentMode').textContent='Modo demonstração'}}
function applyMasks(){
  $('#customerCpf').oninput=e=>{let v=cleanDigits(e.target.value).slice(0,11);e.target.value=v.replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2')};
  $('#customerPhone').oninput=e=>{let v=cleanDigits(e.target.value).slice(0,11);e.target.value=v.replace(/^(\d{2})(\d)/,'($1) $2').replace(/(\d{5})(\d{4})$/,'$1-$2')};
  $('#postalCode').oninput=e=>{let v=cleanDigits(e.target.value).slice(0,8);e.target.value=v.replace(/(\d{5})(\d)/,'$1-$2')};
}
async function submitOrder(event){event.preventDefault();if(!cart.length||!validate())return;if(!apiConfig.paymentsEnabled){$('#checkoutModal').classList.add('open');$('#checkoutModal').setAttribute('aria-hidden','false');return}if(paymentMethod!=='pix'){toast('Os cartões serão processados pelo formulário seguro do Mercado Pago.');return}
  const payload={payment_method_id:'pix',transaction_amount:Number(total().toFixed(2)),description:`Pedido Compartilhe Store (${cart.length} itens)`,payer:{email:$('#customerEmail').value,first_name:$('#customerName').value.split(' ')[0],last_name:$('#customerName').value.split(' ').slice(1).join(' '),identification:{type:'CPF',number:cleanDigits($('#customerCpf').value)}},metadata:{deliveryType,shippingChoice,items:cart}};
  try{$('#placeOrder').disabled=true;const response=await fetch('/api/payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.message||'Falha ao criar cobrança');if(data.point_of_interaction?.transaction_data?.ticket_url)location.href=data.point_of_interaction.transaction_data.ticket_url;else toast('Cobrança Pix criada com sucesso.')}catch(error){toast(error.message)}finally{$('#placeOrder').disabled=false}
}
function init(){renderSummary();setDelivery('pickup');applyMasks();loadConfig();$$('input[name=deliveryType]').forEach(r=>r.onchange=()=>setDelivery(r.value));$$('[data-payment]').forEach(b=>b.onclick=()=>setPayment(b.dataset.payment));$('#calculateShipping').onclick=calculateShipping;$('#postalCode').onblur=()=>{if(cleanDigits($('#postalCode').value).length===8)calculateShipping()};$('#couponButton').onclick=()=>toast('Cupom não encontrado.');$('#checkoutForm').onsubmit=submitOrder;$('#closeCheckoutModal').onclick=()=>$('#checkoutModal').classList.remove('open')}
document.addEventListener('DOMContentLoaded',init);
